#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent
import base64
import os

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

#This is specific to you module, so you need to change it accordingly.

# SMTP
rdb = agent.redis_connect(use_replica=True)
smtp_settings = agent.get_smarthost_settings(rdb)

MAIL_MAILER = "smtp"
MAIL_HOST = smtp_settings["host"]
MAIL_PORT = smtp_settings["port"]
MAIL_USERNAME = smtp_settings["username"]
MAIL_PASSWORD = smtp_settings["password"]
MAIL_ENCRYPTION = smtp_settings["encrypt_smtp"]
MAIL_FROM_ADDRESS=smtp_settings["username"]
MAIL_REPLY_TO_ADDRESS=smtp_settings["username"]

# Application File


APP_URL = data.get("host", "")
app = {
    "APP_URL": "https://"+APP_URL,
    "APP_TRUSTED_PROXIES": "*",
    "APP_ENV": "production",
    "APP_DEBUG": "false",
    "MAIL_MAILER": MAIL_MAILER,
    "MAIL_HOST": MAIL_HOST,
    "MAIL_PORT": MAIL_PORT,
    "MAIL_USERNAME": MAIL_USERNAME,
    "MAIL_PASSWORD": MAIL_PASSWORD,
    "MAIL_ENCRYPTION": MAIL_ENCRYPTION,
    "MAIL_FROM_ADDRESS": MAIL_FROM_ADDRESS,
    "MAIL_REPLY_TO_ADDRESS": MAIL_REPLY_TO_ADDRESS,
    "REDIS_HOST": "monica-redis",
    "REDIS_PORT":"6379",
    "CACHE_DRIVER": "database",
    "SESSION_DRIVER": "database",
    "QUEUE_CONNECTION": "sync",
    "DB_CONNECTION": "mysql",
    "QUEUE_DRIVER": "sync",
}

agent.write_envfile("app.env", app)

# agent.set_env("MONICA_REDIS_PASSWORD", "Monica@redis")


agent.dump_env()
